apiVersion: v1
kind: Pod
metadata:
  name: show-storage
spec:
  volumes:
    - name: task07-pv-storage
      persistentVolumeClaim:
        claimName: task07-pvc1
  containers:
    - name: alpine
      image: alpine
      command: ["sleep","infinity"]
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
      volumeMounts:
        - name: task07-pv-storage
          mountPath: /Write

