apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: task07-pvc1
    # namespace: default
spec:
    # volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
