apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-storage
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: "nfs"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  nfs:
    server: 192.168.120.100
    path: /PV
    readOnly: false


# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: nfs-storage
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: nfs
#   mountOptions:
#     - hard
#     - nfsvers=4.0
#   nfs:
#     path: /PV
#     server: 192.168.120.100
