apiVersion: v1
kind: PersistentVolume
metadata:
  name: task07-pv1
  # namespace: default
spec:
  capacity:
    storage: 2Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/PV"
